name: CI/CD Pipeline for FE

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker image for frontend using docker-compose
        run: |
          docker-compose build

      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/et-react:latest

      - name: Deploy to Server with docker-compose
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REACT_EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu
            docker-compose pull
            docker-compose down || true
            docker-compose up -d